import { createAudioPlayer } from 'expo-audio';

// Pre-generated by scripts/gen-earcons.mjs. The sweeps (start 660→990 Hz, stop 660→440 Hz,
// 120 ms, sin(πt) envelope) are the shared intercom earcons across CLI/web/Android.
const START = require('../../assets/earcons/record-start.wav');
const STOP = require('../../assets/earcons/record-stop.wav');

function play(source: number) {
  const player = createAudioPlayer(source);
  player.play();
  // Release the native player once the short clip is done.
  setTimeout(() => player.remove(), 1000);
}

export function playRecordStart() {
  play(START);
}

export function playRecordStop() {
  play(STOP);
}
